### ISSUE TITLE
Merge the OpenMP and basic versions of package

### ISSUE THREAD

**Issue by cabouman** [cabouman/cython_sandbox#14]
We need to create a single integrated version of the package. To do this, we need to do two things:

1.  First, update the existing openmp branch by merging in the main branch. This will bring the code up to date.
2. Use a bash environment variable to determine if OpenMP compilation is done.

You can use the environment variable:
> SANDBOXOMP="ON"

with the default compilation being without OMP compilation. So then the syntax for compilation with OMP would be **something like**:

>SANDBOXOMP="ON"
>CC=clang SANDBOXOMP="ON" python setup.py install

Also, the README.md will need to be updated to explain this.

**Comment by DamonLee5** [comment]
So do you mean that by setting the environment variable SANDBOXOMP= "ON",  we can do Conditional Compilation based on Environmental Variable?

We should also add something likes the below in the matrices.c

`#if SANDBOXOMP == "ON"`
`#include <omp.h>`
`#endif`

**Comment by cabouman** [comment]
Yes, correct. Make sure to update your development branch with the main branch first, so you have rolled in all our changes. Then add in these OMP enhancements into your development branch. 

Once I approve your ``openmp`` branch, then we can integrate it into the main branch with a pull request.

**Comment by cabouman** [comment]
I merged an OpenMP version of the code into the main branch. You can compile using OpenMP with the ``gcc`` compiler with the command:

`OMPCOMP=1 CC=gcc pip install .`

However, the bad news is that the OpenMP version is about 10x slower than the single threaded ``gcc`` version. So we need to figure that out.

**Comment by DamonLee5** [comment]
> I merged an OpenMP version of the code into the main branch. You can compile using OpenMP with the `gcc` compiler with the command:
> 
> `OMPCOMP=1 CC=gcc pip install .`
> 
> However, the bad news is that the OpenMP version is about 10x slower than the single threaded `gcc` version. So we need to figure that out.

I found a solution, we should just move `#pragma omp parallel for` to the outer loop.
From:

    /* Compute matrix product */
    for (i = 0; i < A->NRows ; i ++ )
        #pragma omp parallel for
        for (j = 0; j < B->NCols ; j ++ ) {
            C->mat[i][j] = 0;
            for (k = 0; k < A->NCols ; k ++ )
                C->mat[i][j] += A->mat[i][k]*B->mat[k][j];
        }

To:

    /* Compute matrix product */
    #pragma omp parallel for
    for (i = 0; i < A->NRows ; i ++ )
        for (j = 0; j < B->NCols ; j ++ ) {
            C->mat[i][j] = 0;
            for (k = 0; k < A->NCols ; k ++ )
                C->mat[i][j] += A->mat[i][k]*B->mat[k][j];
        }

Then, it will be 2x faster than the single-threaded gcc version.

**Comment by cabouman** [comment]
Excellent! It's merged into the main branch. 

Now we just have to get the icc compiler work with OpenMP.
