### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by cabouman** [cabouman/cython_sandbox#3]
Make sure to retype C variable to eliminate all C compiler warnings.

**Comment by cabouman** [comment]
Jordan, the clang compiler is complaining about some typing issues in the ``multialloc()`` code. In particular it doesn't like line 118 because ``j`` has type ``int`` and ``max`` has type ``size_t``. 

Should we change the typing of `i` and `j` in line 85 to ``size_t``?

And if we do this, should we change it in other occurrences of allocate.c?

**Comment by sjkisner** [comment]
@cabouman Strange I haven't seen that warning.

Changing "j" to "size_t" is safer and from your description should make the warning go away. Do you want to make the change and confirm it fixes the warning?

"i" is safe to leave as "int". If you change it it might generate a different warning.
