### ISSUE TITLE
Poor memory efficiency

### ISSUE THREAD

**Issue by bwohlberg** [cabouman/cython_sandbox#8]
This implementation is very inefficient in its use of unnecessary memory allocation and copy operations:

https://github.com/cabouman/cython_sandbox/blob/939174e386c804041d6dc80f3629e18ba17447a9/cython_sandbox/wrapped.pyx#L37-L62

The correct approach would be to set
```
A.mat = &temp_a[0, 0]
B.mat = &temp_b[0, 0]
```
to avoid copying of the input matrices. When allocating output arrays, it's usually simpler to use `np.zeros` (or, more efficiently, `np.empty`) than a custom function as has been used here. Finally, since one of the main purposes of Cython is to provide a Python-like interface to C code, it would make more sense for `py_matrix_multiplication` to take two arrays as arguments and return a reference to the result, as is the case for almost all NumPy functions.

For examples of how to do this, see function `_cbpdn` in the [Cython wrapper for sporco-cuda](https://github.com/bwohlberg/sporco-cuda/blob/master/sporco_cuda/cbpdn.pyx).

**Comment by cabouman** [comment]
Brendt, I more-or-less fixed the problem and pushed it to the main branch. 

The way I handled it was to allocate and deallocate the pointer array within the C subroutine. I did this by adding an additional element to the structure A->mat_pt , that keeps track of the memory block, and by writing some simple utilities that convert to and from the multialloc() 2D format. This eliminates the need to do weird C-like memory allocations in the python code.

However, I'm still not sure that I'm doing things in the best way in the main routine that is [here](https://github.com/cabouman/cython_sandbox/blob/main/cython_sandbox/wrapped.pyx). In particular, I'm not sure I completely understand what is going on with the ``temp_c``, ``py_c``, and ``C`` structures. So I might not be doing things in the most efficient way.

So this thing may still need more work.

**Comment by bwohlberg** [comment]
Charlie,

There's obviously going to be an overhead from all the memory
allocation and copying, but I guess it's unavoidable if the use of
pointer arrays is baked into the C code. Let me know if you'd like to
discuss this further.

Brendt

**Comment by cabouman** [comment]
Right now it appears that ``temp_c`` and ``py_c`` are being stored in separate memory which is inefficient. I'm not sure about ``temp_a``,  ``py_a``, ``temp_b``, and ``py_b``. In order to resolve this issue, we need to:

1.  Read the available information on cython to better understand how it is handling memory arrays and allocation.
2. Determine if we can directly allocate ``temp_c`` without first creating ``py_c``.
3. If the document is unclear, as a last resort we can use profiling tools to determine if we have duplicate memory arrays for ``temp_a``,  ``py_a``, ``temp_b``, and ``py_b``.

**Comment by DamonLee5** [comment]
>2. Determine if we can directly allocate `temp_c` without first creating `py_c`.

We can directly allocate temp_c by 
`cdef np.ndarray[float, ndim=2, mode="c"] temp_c = np.zeros((nrows_a,ncols_b),dtype = ctypes.c_float)`
 np.zeros will create a contiguous array, we don't need to use np.ascontiguousarray to make it as a contiguous array.

>3. If the document is unclear, as a last resort we can use profiling tools to determine if we have duplicate memory arrays for `temp_a`, `py_a`, `temp_b`, and `py_b`.

`py_a` and `py_b` are input from users, which may not a contiguous array and we should never use it as the input for the c functions.
`np.ascontiguousarray` returns a contiguous array from the input array instead of transfer an uncontiguous array to a contiguous array.
From my point of view, we should have duplicate memory arrays for `temp_a`, `py_a`, `temp_b`, and `py_b`.

I already allocated `temp_c` without first creating `py_c` in wenrui branch. Maybe I can make a pull request for it.

**Comment by sjkisner** [comment]
> `py_a` and `py_b` are input from users, which may not a contiguous array and we should never use it as the input for the c functions.

@DamonLee5 Can you do a check for contiguity and only duplicate the memory if it's necessary? There's a flags attribute that can tell you if it's C-style contiguous. [see this](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html#numpy.ndarray.flags)

I ask because in the svmbir package I'm already working with problems sizes where there wouldn't be enough memory available to duplicate the input or output arrays.

**Comment by cabouman** [comment]
I made an update of the main branch that does the more efficient allocation for ``temp_c``. I also tested it, and it seems to work fine.

It's not clear to me if the line
`cdef np.ndarray[float, ndim=2, mode="c"] temp_a = np.ascontiguousarray(py_a, dtype = ctypes.c_float)`
copies memory or just pointers. It might depend on whether the structure ``py_a`` is already contiguous. 

In any case, Jordan is correct. We don't want to copy memory if we don't have to.
In most cases, py_a will already be contiguous. 
So we need to find out exactly how Cython handles this, and make sure the example is optimized.

**Comment by bwohlberg** [comment]
> We can directly allocate temp_c by
> `cdef np.ndarray[float, ndim=2, mode="c"] temp_c = np.zeros((nrows_a,ncols_b),dtype = ctypes.c_float)`
> np.zeros will create a contiguous array, we don't need to use np.ascontiguousarray to make it as a contiguous array.

I agree with this approach, but if you're certain that every index in `temp_c` is written to, you can make the allocation a bit more efficient by using `np.empty` instead of `np.zeros`.

> `py_a` and `py_b` are input from users, which may not a contiguous array and we should never use it as the input for the c functions.
> `np.ascontiguousarray` returns a contiguous array from the input array instead of transfer an uncontiguous array to a contiguous array.
> From my point of view, we should have duplicate memory arrays for `temp_a`, `py_a`, `temp_b`, and `py_b`.

I'm not a fan of this approach. Copying large arrays when it's not necessary can represent a significant computational overhead, and waste precious memory resources (see related comment by @sjkisner). My suggestion would be:
* avoid copying, making use of the C arrays internal to `py_a` and `py_b`, passing the responsibility of passing in contiguous arrays on to the user
* document the contiguous array requirement
* check the arrays and raise exceptions if either of them is not contiguous, or not in the correct order (i.e. 'F' rather than 'C')

**Comment by bwohlberg** [comment]
> It's not clear to me if the line
> `cdef np.ndarray[float, ndim=2, mode="c"] temp_a = np.ascontiguousarray(py_a, dtype = ctypes.c_float)`
> copies memory or just pointers. It might depend on whether the structure `py_a` is already contiguous.

My understanding is that `np.ascontiguousarray` does nothing if the array is already contiguous (and in the correct C/F order), and does a copy otherwise.

**Comment by DamonLee5** [comment]
> > `py_a` and `py_b` are input from users, which may not a contiguous array and we should never use it as the input for the c functions.
> 
> @DamonLee5 Can you do a check for contiguity and only duplicate the memory if it's necessary? There's a flags attribute that can tell you if it's C-style contiguous. [see this](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html#numpy.ndarray.flags)
> 
> I ask because in the svmbir package I'm already working with problems sizes where there wouldn't be enough memory available to duplicate the input or output arrays.

After I did some research on ascontiguousarray, I notice that it will copy object only when the input is a noncontinuous array.
[ascontiguousarray(https://github.com/numpy/numpy/blob/v1.8.0/numpy/core/numeric.py#L514)
[np.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

**Comment by DamonLee5** [comment]
> > We can directly allocate temp_c by
> > `cdef np.ndarray[float, ndim=2, mode="c"] temp_c = np.zeros((nrows_a,ncols_b),dtype = ctypes.c_float)`
> > np.zeros will create a contiguous array, we don't need to use np.ascontiguousarray to make it as a contiguous array.
> 
> I agree with this approach, but if you're certain that every index in `temp_c` is written to, you can make the allocation a bit more efficient by using `np.empty` instead of `np.zeros`.
> 
> > `py_a` and `py_b` are input from users, which may not a contiguous array and we should never use it as the input for the c functions.
> > `np.ascontiguousarray` returns a contiguous array from the input array instead of transfer an uncontiguous array to a contiguous array.
> > From my point of view, we should have duplicate memory arrays for `temp_a`, `py_a`, `temp_b`, and `py_b`.
> 
> I'm not a fan of this approach. Copying large arrays when it's not necessary can represent a significant computational overhead, and waste precious memory resources (see related comment by @sjkisner). My suggestion would be:
> 
> * avoid copying, making use of the C arrays internal to `py_a` and `py_b`, passing the responsibility of passing in contiguous arrays on to the user
> * document the contiguous array requirement
> * check the arrays and raise exceptions if either of them is not contiguous, or not in the correct order (i.e. 'F' rather than 'C')



> > We can directly allocate temp_c by
> > `cdef np.ndarray[float, ndim=2, mode="c"] temp_c = np.zeros((nrows_a,ncols_b),dtype = ctypes.c_float)`
> > np.zeros will create a contiguous array, we don't need to use np.ascontiguousarray to make it as a contiguous array.
> 
> I agree with this approach, but if you're certain that every index in `temp_c` is written to, you can make the allocation a bit more efficient by using `np.empty` instead of `np.zeros`.
> 
> > `py_a` and `py_b` are input from users, which may not a contiguous array and we should never use it as the input for the c functions.
> > `np.ascontiguousarray` returns a contiguous array from the input array instead of transfer an uncontiguous array to a contiguous array.
> > From my point of view, we should have duplicate memory arrays for `temp_a`, `py_a`, `temp_b`, and `py_b`.
> 
> I'm not a fan of this approach. Copying large arrays when it's not necessary can represent a significant computational overhead, and waste precious memory resources (see related comment by @sjkisner). My suggestion would be:
> 
> * avoid copying, making use of the C arrays internal to `py_a` and `py_b`, passing the responsibility of passing in contiguous arrays on to the user
> * document the contiguous array requirement
> * check the arrays and raise exceptions if either of them is not contiguous, or not in the correct order (i.e. 'F' rather than 'C')

Okay. So now I have another question. If we try to change datatype of the input, will we do a copy?

**Comment by bwohlberg** [comment]
> Okay. So now I have another question. If we try to change datatype of the input, will we do a copy?

Yes.

I suggest also making the data type (e.g. `np.float32`) part of the interface specification.

**Comment by cabouman** [comment]
I think this is fully fixed in the main branch.
